matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_install:
        - cd ./Front-end
      cache:
        - npm
      install:
        - npm ci
      script:
        - npm run build
    - language: python
      python:
        - "3.6"
      cache:
        - pip
      before_install:
        - cd ./Back-end
      install:
        - pip install django --quiet
      script:
        - python manage.py test
      after_success:
        - cd ..
        - git subtree push --prefix Back-end origin server
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
