matrix:
  include:
    - language: node_js
      node_js:
        - stable
      cache:
        - ./Front-end/node_modules
      before_install:
        - cd ./Front-end
      script:
        - npm run build
    - language: node_js
      services:
        - mongodb
      node_js:
        - stable
      cache:
        - ./Back-end/node_modules
      before_script:
        - mongorestore --port 27017 -d test ./src/test/db
      before_install:
        - cd ./Back-end
      after_success:
        - cd ..
        - git subtree push --prefix Back-end origin server

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
